spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: 'org.hibernate.dialect.MySQL8Dialect'

    hibernate:
      ddl-auto: none


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
          sql: trace

